# Generated by Django 3.1.7 on 2021-03-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210319_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
