# Generated by Django 3.1.7 on 2021-03-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription'),
        ),
        migrations.AddField(
            model_name='optionproduct',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.option'),
        ),
        migrations.AddField(
            model_name='optionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ManyToManyField(through='product.OptionProduct', to='product.Product'),
        ),
        migrations.AddField(
            model_name='option',
            name='subscription',
            field=models.ManyToManyField(through='product.OptionSubscription', to='subscription.Subscription'),
        ),
    ]
