# Generated by Django 3.1.7 on 2021-03-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
