# Generated by Django 3.1.7 on 2021-03-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20210317_1146'),
        ('product', '0003_option_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='subscription',
            field=models.ManyToManyField(to='subscription.Subscription'),
        ),
    ]
