# Generated by Django 3.1.7 on 2021-03-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('subscription', '0002_auto_20210317_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='introduction',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='monthly_plan',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=0, default='', max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
            ],
            options={
                'db_table': 'subscription_details',
            },
        ),
    ]
