# Generated by Django 3.1.7 on 2021-03-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20210317_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionDetail',
            new_name='Detail',
        ),
    ]
