# Generated by Django 3.1.7 on 2021-03-18 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_rate', models.FloatField()),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'LessonLocations',
            },
        ),
        migrations.CreateModel(
            name='OnedayLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desctiption', models.CharField(max_length=500)),
                ('ondday_lesson', models.ManyToManyField(through='lesson.LessonLocation', to='lesson.OnedayLesson')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.AddField(
            model_name='lessonlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.location'),
        ),
        migrations.AddField(
            model_name='lessonlocation',
            name='onedaylesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.onedaylesson'),
        ),
    ]
