# Generated by Django 3.1.7 on 2021-03-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('category', '0001_initial'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnedayLesson',
            new_name='Lesson',
        ),
        migrations.RenameField(
            model_name='lessonlocation',
            old_name='onedaylesson',
            new_name='lesson',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='lessons',
        ),
        migrations.AlterModelTable(
            name='lessonlocation',
            table='lessonlocations',
        ),
    ]
