# Generated by Django 3.1.7 on 2021-03-19 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=50, null=True)),
                ('recipient', models.CharField(max_length=100)),
                ('recipient_phone_number', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('save_option', models.BooleanField()),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='LessonCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending_date', models.DateField(default=datetime.datetime(2021, 3, 19, 13, 33, 0, 875585), null=True, verbose_name='attending_date')),
            ],
            options={
                'db_table': 'lessoncarts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'paymentmethods',
            },
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('delivery_date', models.DateField(default=datetime.datetime(2021, 3, 19, 13, 33, 0, 874717), null=True, verbose_name='delivery_date')),
            ],
            options={
                'db_table': 'productcarts',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('delivery_date', models.DateField(default=datetime.datetime(2021, 3, 19, 13, 33, 0, 875179), null=True, verbose_name='delivery_date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'subscriptionscarts',
            },
        ),
    ]
