# Generated by Django 3.1.7 on 2021-03-18 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        ('product', '0001_initial'),
        ('lesson', '0002_auto_20210318_1917'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcart',
            old_name='optionproduct',
            new_name='option_product',
        ),
        migrations.AddField(
            model_name='productcart',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 18, 19, 17, 29, 371105), null=True, verbose_name='delivery_date'),
        ),
        migrations.AddField(
            model_name='productcart',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterModelTable(
            name='productcart',
            table='productcarts',
        ),
        migrations.CreateModel(
            name='SubscriptionCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('delivery_date', models.DateField(default=datetime.datetime(2021, 3, 18, 19, 17, 29, 371442), null=True, verbose_name='delivery_date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
                ('subscription_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.optionsubscription')),
            ],
            options={
                'db_table': 'subscriptionscarts',
            },
        ),
        migrations.CreateModel(
            name='LessonCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending_date', models.DateField(default=datetime.datetime(2021, 3, 18, 19, 17, 29, 371869), null=True, verbose_name='attending_date')),
                ('lesson_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lessonlocation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'lessoncarts',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='lesson_location',
            field=models.ManyToManyField(through='order.LessonCart', to='lesson.LessonLocation'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ManyToManyField(through='order.SubscriptionCart', to='subscription.Subscription'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_option',
            field=models.ManyToManyField(through='order.SubscriptionCart', to='product.OptionSubscription'),
        ),
    ]
