# Generated by Django 3.1.7 on 2021-03-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20210323_1029'),
        ('order', '0001_initial'),
        ('product', '0001_initial'),
        ('subscription', '0001_initial'),
        ('lesson', '0002_auto_20210323_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioncart',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptioncart',
            name='subscription_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.optionsubscription'),
        ),
        migrations.AddField(
            model_name='productcart',
            name='option_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.optionproduct'),
        ),
        migrations.AddField(
            model_name='productcart',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='productcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='lesson_location',
            field=models.ManyToManyField(through='order.LessonCart', to='lesson.LessonLocation'),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.paymentmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='order.ProductCart', to='product.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_option',
            field=models.ManyToManyField(through='order.ProductCart', to='product.OptionProduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.status'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_option',
            field=models.ManyToManyField(through='order.SubscriptionCart', to='product.OptionSubscription'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscriptionplan',
            field=models.ManyToManyField(through='order.SubscriptionCart', to='subscription.SubscriptionPlan'),
        ),
        migrations.AddField(
            model_name='lessoncart',
            name='lesson_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lessonlocation'),
        ),
        migrations.AddField(
            model_name='lessoncart',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
