# Generated by Django 3.1.7 on 2021-03-19 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20210319_1355'),
        ('order', '0002_auto_20210319_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subscription',
        ),
        migrations.AddField(
            model_name='order',
            name='subscriptionplan',
            field=models.ManyToManyField(through='order.SubscriptionCart', to='subscription.SubscriptionPlan'),
        ),
        migrations.AlterField(
            model_name='lessoncart',
            name='attending_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 13, 55, 21, 589908), null=True, verbose_name='attending_date'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 13, 55, 21, 588986), null=True, verbose_name='delivery_date'),
        ),
        migrations.AlterField(
            model_name='subscriptioncart',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 13, 55, 21, 589428), null=True, verbose_name='delivery_date'),
        ),
        migrations.AlterField(
            model_name='subscriptioncart',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionplan'),
        ),
    ]
