# Generated by Django 3.1.7 on 2021-03-19 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210319_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncart',
            name='attending_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 13, 56, 37, 49746), null=True, verbose_name='attending_date'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 13, 56, 37, 49049), null=True, verbose_name='delivery_date'),
        ),
        migrations.AlterField(
            model_name='subscriptioncart',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 13, 56, 37, 49409), null=True, verbose_name='delivery_date'),
        ),
        migrations.AlterModelTable(
            name='lessoncart',
            table='lesson_carts',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='payment_methods',
        ),
        migrations.AlterModelTable(
            name='productcart',
            table='product_carts',
        ),
        migrations.AlterModelTable(
            name='subscriptioncart',
            table='subscriptions_carts',
        ),
    ]
